"""Detached local runs: one directory per run, survives the dashboard.

A run is a shell script written to disk and started with ``setsid`` under the
node's worktree, leaving ``run.sh``, ``log``, ``pid`` and ``exit_code`` behind
(the layout OpenResearch's localbox uses). Because the state is on disk, the
dashboard can be restarted mid-experiment and still adopt live runs and read
finished ones.

Scores are never taken from a worker's claim: ``extract_score`` greps the run's
own log with the project's ``metric_grep`` pattern.
"""

from __future__ import annotations

import os
import re
import signal
import subprocess
import time
from dataclasses import dataclass
from pathlib import Path

RUN_SH = "run.sh"
LOG = "log"
PID = "pid"
EXIT_CODE = "exit_code"

# The command runs in a subshell so an ``exit`` inside it still lands on the
# ``exit_code`` write — that file is how a restarted dashboard learns a run's
# outcome.
_SCRIPT = """#!/bin/sh
# generated by agentfork; do not edit
cd {cwd} || exit 127
(
{command}
)
status=$?
printf '%s' "$status" > {exit_code}
exit $status
"""


class RunError(RuntimeError):
    pass


@dataclass
class RunHandle:
    run_dir: Path
    pid: int

    @property
    def log_path(self) -> Path:
        return self.run_dir / LOG


def start(run_dir: str | Path, command: str, cwd: str | Path, *,
          env: dict[str, str] | None = None) -> RunHandle:
    """Start ``command`` detached, writing its artifacts into ``run_dir``."""
    run_dir = Path(run_dir)
    run_dir.mkdir(parents=True, exist_ok=True)
    script = run_dir / RUN_SH
    script.write_text(_SCRIPT.format(cwd=_quote(str(cwd)), command=command,
                                     exit_code=_quote(str(run_dir / EXIT_CODE))))
    script.chmod(0o755)
    log = (run_dir / LOG).open("ab")
    try:
        proc = subprocess.Popen(
            ["/bin/sh", str(script)], cwd=str(cwd), stdin=subprocess.DEVNULL,
            stdout=log, stderr=subprocess.STDOUT, start_new_session=True,
            env={**os.environ, **(env or {})})
    finally:
        log.close()
    (run_dir / PID).write_text(str(proc.pid))
    return RunHandle(run_dir, proc.pid)


def _quote(path: str) -> str:
    return "'" + path.replace("'", "'\\''") + "'"


def exit_code(run_dir: str | Path) -> int | None:
    path = Path(run_dir) / EXIT_CODE
    if not path.exists():
        return None
    text = path.read_text().strip()
    return int(text) if text else None


def pid(run_dir: str | Path) -> int | None:
    path = Path(run_dir) / PID
    if not path.exists():
        return None
    text = path.read_text().strip()
    return int(text) if text else None


def alive(run_dir: str | Path) -> bool:
    """A run is alive while it has a pid, no exit code, and a live process.

    A run killed by a signal never gets to write ``exit_code``, and while the
    dashboard is its parent the dead process lingers as an unreaped zombie —
    which still answers ``kill(pid, 0)``. So reap it if it is ours and treat a
    zombie as dead.
    """
    if exit_code(run_dir) is not None:
        return False
    p = pid(run_dir)
    if p is None:
        return False
    try:
        reaped, _ = os.waitpid(p, os.WNOHANG)
        if reaped == p:
            return False
    except ChildProcessError:
        pass   # not our child (adopted from a previous dashboard process)
    except OSError:
        return False
    try:
        os.kill(p, 0)
    except ProcessLookupError:
        return False
    except PermissionError:
        return True
    return not _zombie(p)


def _zombie(p: int) -> bool:
    try:
        stat = Path(f"/proc/{p}/stat").read_text()
    except OSError:
        return True
    # field 3 is the state; the comm field before it may contain spaces
    tail = stat.rpartition(")")[2].split()
    return bool(tail) and tail[0] == "Z"


def kill(run_dir: str | Path, *, grace_s: float = 3.0) -> bool:
    """SIGTERM the run's process group, SIGKILL if it outlives the grace."""
    p = pid(run_dir)
    if p is None:
        return False
    try:
        pgid = os.getpgid(p)
    except ProcessLookupError:
        return False
    for sig, wait in ((signal.SIGTERM, grace_s), (signal.SIGKILL, 0.2)):
        try:
            os.killpg(pgid, sig)
        except ProcessLookupError:
            return True
        deadline = time.monotonic() + wait
        while time.monotonic() < deadline:
            if not alive(run_dir):
                return True
            time.sleep(0.05)
    return not alive(run_dir)


def tail(run_dir: str | Path, *, offset: int = 0,
         limit: int = 200_000) -> tuple[str, int]:
    """Read up to ``limit`` bytes of the log from ``offset``.

    Returns the text and the new offset, so the dashboard can poll/stream
    incrementally without re-reading a large log.
    """
    path = Path(run_dir) / LOG
    if not path.exists():
        return "", offset
    size = path.stat().st_size
    if offset > size:   # log truncated/rotated underneath us
        offset = 0
    with path.open("rb") as f:
        f.seek(offset)
        chunk = f.read(limit)
    return chunk.decode("utf-8", "replace"), offset + len(chunk)


def extract_score(run_dir: str | Path, metric_grep: str, *,
                  last: bool = True) -> float | None:
    """Grep the run's log for the metric. The pattern's first capture group
    (or the whole match) must be the number; ``last`` takes the final
    occurrence, which is what an eval that prints per-epoch lines needs."""
    # scores land at the end of the log; read the tail, not the head
    path = Path(run_dir) / LOG
    size = path.stat().st_size if path.exists() else 0
    text, _ = tail(run_dir, offset=max(0, size - 8_000_000), limit=8_000_000)
    matches = re.findall(metric_grep, text)
    if not matches:
        return None
    picked = matches[-1] if last else matches[0]
    if isinstance(picked, tuple):
        picked = next((g for g in picked if g), "")
    try:
        return float(_NUM.search(str(picked)).group(0))  # type: ignore[union-attr]
    except (AttributeError, ValueError):
        return None


_NUM = re.compile(r"[-+]?\d*\.?\d+(?:[eE][-+]?\d+)?")
